/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmpManagement;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Subriti
 */
public class Registration extends javax.swing.JFrame {

    String query;
    Connection con;
    Statement st;
    ResultSet rs;
    ResultSetMetaData rsmd;
    DefaultTableModel model;

    String table;
    int count;

    String fname, lname, address, email, salary, dept_id, post_id, update_date;

    String pid, pcode, pname, pdate;

    String did, dcode, dname, ddate;

    /**
     * Creates new form ExecuteQueries
     */
    public Registration() {
        initComponents();

        MainPanel.setVisible(true);
        LoginPanel.setVisible(true);
        MainPage.setVisible(false);
        AddDept.setVisible(false);
        AddEmp.setVisible(false);
        AddPost.setVisible(false);

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employeedetails", "root", "");
            st = con.createStatement();

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }

        DisplayEmpDetails();
        DisplayPostDetails();
        DisplayDeptDetails();
        
        SetIcon();
    }
    
    private void SetIcon() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("UserIcon.jpg"));
        setIconImage(icon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEmp = new javax.swing.JPanel();
        Empregistration_jLabel = new javax.swing.JLabel();
        fname_jLabel = new javax.swing.JLabel();
        fname_jTextField = new javax.swing.JTextField();
        address_jLabel = new javax.swing.JLabel();
        salary_jLabel = new javax.swing.JLabel();
        salary_jTextField = new javax.swing.JTextField();
        date_jLabel = new javax.swing.JLabel();
        pid_jLabel = new javax.swing.JLabel();
        did_jLabel = new javax.swing.JLabel();
        dept_jTextField = new javax.swing.JTextField();
        clearEmpRegistration_jButton = new javax.swing.JButton();
        backEmpRegistration_jButton = new javax.swing.JButton();
        Empadd_jButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        address_jTextArea = new javax.swing.JTextArea();
        email_jLabel = new javax.swing.JLabel();
        email_jTextField = new javax.swing.JTextField();
        Empupdate_jButton = new javax.swing.JButton();
        Empdelete_jButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Emp_jTable = new javax.swing.JTable();
        post_jTextField = new javax.swing.JTextField();
        date_jTextField = new javax.swing.JTextField();
        lname_jTextField = new javax.swing.JTextField();
        lname_jLabel = new javax.swing.JLabel();
        AddDept = new javax.swing.JPanel();
        Deptregistration_jLabel = new javax.swing.JLabel();
        name_jLabel1 = new javax.swing.JLabel();
        dcode_jTextField = new javax.swing.JTextField();
        age_jLabel1 = new javax.swing.JLabel();
        ddate_jTextField = new javax.swing.JTextField();
        username_jLabel1 = new javax.swing.JLabel();
        dname_jTextField = new javax.swing.JTextField();
        clearDeptRegistration_jButton = new javax.swing.JButton();
        backDeptRegistration_jButton = new javax.swing.JButton();
        Deptadd_jButton = new javax.swing.JButton();
        mobile_jLabel1 = new javax.swing.JLabel();
        did_jTextField = new javax.swing.JTextField();
        Deptupdate_jButton = new javax.swing.JButton();
        Deptdelete_jButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Dept_jTable = new javax.swing.JTable();
        MainPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Emp_b = new javax.swing.JButton();
        Dept_b = new javax.swing.JButton();
        Post_b = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        QueryResult_jTable = new javax.swing.JTable();
        SubmitQuery = new javax.swing.JButton();
        AddPost = new javax.swing.JPanel();
        Postregistration_jLabel = new javax.swing.JLabel();
        pcode_jLabel = new javax.swing.JLabel();
        pcode_jTextField = new javax.swing.JTextField();
        pdate_jLabel = new javax.swing.JLabel();
        pdate_jTextField = new javax.swing.JTextField();
        pname_jLabel = new javax.swing.JLabel();
        pname_jTextField = new javax.swing.JTextField();
        clearPostRegistration_jButton = new javax.swing.JButton();
        backPostRegistration_jButton = new javax.swing.JButton();
        Postadd_jButton = new javax.swing.JButton();
        pID_jLabel = new javax.swing.JLabel();
        pid_jTextField = new javax.swing.JTextField();
        Postupdate_jButton = new javax.swing.JButton();
        Postdelete_jButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        Post_jTable = new javax.swing.JTable();
        MainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        loginuser_jLabel = new javax.swing.JLabel();
        loginpass_jLabel = new javax.swing.JLabel();
        user_jTextField = new javax.swing.JTextField();
        login_jButton = new javax.swing.JButton();
        loginclear_jButton = new javax.swing.JButton();
        pass_jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");

        AddEmp.setBackground(new java.awt.Color(204, 204, 255));
        AddEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        Empregistration_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        Empregistration_jLabel.setText("Employee Registration");
        Empregistration_jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        fname_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        fname_jLabel.setText("First Name: ");

        fname_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        fname_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        address_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        address_jLabel.setText("Address:");

        salary_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        salary_jLabel.setText("Salary:");

        salary_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        salary_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        date_jLabel.setText("Update Date:");

        pid_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        pid_jLabel.setText("Post ID:");

        did_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        did_jLabel.setText("Department ID:");

        dept_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        dept_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        clearEmpRegistration_jButton.setBackground(new java.awt.Color(0, 0, 0));
        clearEmpRegistration_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        clearEmpRegistration_jButton.setForeground(new java.awt.Color(153, 153, 255));
        clearEmpRegistration_jButton.setText("Clear");
        clearEmpRegistration_jButton.setBorder(null);
        clearEmpRegistration_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEmpRegistration_jButtonActionPerformed(evt);
            }
        });

        backEmpRegistration_jButton.setBackground(new java.awt.Color(0, 0, 0));
        backEmpRegistration_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        backEmpRegistration_jButton.setForeground(new java.awt.Color(153, 153, 255));
        backEmpRegistration_jButton.setText("Back");
        backEmpRegistration_jButton.setBorder(null);
        backEmpRegistration_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backEmpRegistration_jButtonActionPerformed(evt);
            }
        });

        Empadd_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Empadd_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Empadd_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Empadd_jButton.setText("Add");
        Empadd_jButton.setBorder(null);
        Empadd_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empadd_jButtonActionPerformed(evt);
            }
        });

        address_jTextArea.setBackground(new java.awt.Color(233, 233, 254));
        address_jTextArea.setColumns(20);
        address_jTextArea.setRows(5);
        address_jTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(address_jTextArea);

        email_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        email_jLabel.setText("Email:");

        email_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        email_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Empupdate_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Empupdate_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Empupdate_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Empupdate_jButton.setText("Update");
        Empupdate_jButton.setBorder(null);
        Empupdate_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empupdate_jButtonActionPerformed(evt);
            }
        });

        Empdelete_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Empdelete_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Empdelete_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Empdelete_jButton.setText("Delete");
        Empdelete_jButton.setBorder(null);
        Empdelete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empdelete_jButtonActionPerformed(evt);
            }
        });

        Emp_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Emp_jTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Emp_jTable);

        post_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        post_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        date_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        date_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lname_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        lname_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lname_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        lname_jLabel.setText("Last Name: ");

        javax.swing.GroupLayout AddEmpLayout = new javax.swing.GroupLayout(AddEmp);
        AddEmp.setLayout(AddEmpLayout);
        AddEmpLayout.setHorizontalGroup(
            AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmpLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(Empadd_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Empupdate_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Empdelete_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEmpLayout.createSequentialGroup()
                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddEmpLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(Empregistration_jLabel)
                        .addGap(155, 155, 155)
                        .addComponent(backEmpRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddEmpLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addComponent(fname_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(fname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addComponent(lname_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addComponent(address_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addComponent(salary_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddEmpLayout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(AddEmpLayout.createSequentialGroup()
                                                    .addComponent(did_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4)
                                                    .addComponent(dept_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(AddEmpLayout.createSequentialGroup()
                                                    .addComponent(pid_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4)
                                                    .addComponent(post_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(AddEmpLayout.createSequentialGroup()
                                                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(date_jLabel)
                                                    .addComponent(email_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(date_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                    .addComponent(email_jTextField)))))
                                    .addGroup(AddEmpLayout.createSequentialGroup()
                                        .addComponent(salary_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clearEmpRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(20, 20, 20))
        );
        AddEmpLayout.setVerticalGroup(
            AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Empregistration_jLabel)
                    .addComponent(backEmpRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEmpLayout.createSequentialGroup()
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(fname_jLabel)))
                        .addGap(11, 11, 11)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lname_jLabel)))
                        .addGap(11, 11, 11)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(address_jLabel))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(salary_jLabel))
                            .addComponent(salary_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Empadd_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empupdate_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empdelete_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddEmpLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dept_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(did_jLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(post_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(pid_jLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(date_jLabel)
                                .addGap(24, 24, 24)
                                .addGroup(AddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email_jLabel)
                                    .addComponent(email_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(clearEmpRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AddDept.setBackground(new java.awt.Color(204, 204, 255));
        AddDept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        Deptregistration_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        Deptregistration_jLabel.setText("Department Registration");
        Deptregistration_jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        name_jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        name_jLabel1.setText("Department Code:");

        dcode_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        dcode_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        age_jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        age_jLabel1.setText("Update Date:");

        ddate_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        ddate_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        username_jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        username_jLabel1.setText("Department Name:");

        dname_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        dname_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        clearDeptRegistration_jButton.setBackground(new java.awt.Color(0, 0, 0));
        clearDeptRegistration_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        clearDeptRegistration_jButton.setForeground(new java.awt.Color(153, 153, 255));
        clearDeptRegistration_jButton.setText("Clear");
        clearDeptRegistration_jButton.setBorder(null);
        clearDeptRegistration_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDeptRegistration_jButtonActionPerformed(evt);
            }
        });

        backDeptRegistration_jButton.setBackground(new java.awt.Color(0, 0, 0));
        backDeptRegistration_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        backDeptRegistration_jButton.setForeground(new java.awt.Color(153, 153, 255));
        backDeptRegistration_jButton.setText("Back");
        backDeptRegistration_jButton.setBorder(null);
        backDeptRegistration_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDeptRegistration_jButtonActionPerformed(evt);
            }
        });

        Deptadd_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Deptadd_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Deptadd_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Deptadd_jButton.setText("Add");
        Deptadd_jButton.setBorder(null);
        Deptadd_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deptadd_jButtonActionPerformed(evt);
            }
        });

        mobile_jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        mobile_jLabel1.setText("Department ID:");

        did_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        did_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Deptupdate_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Deptupdate_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Deptupdate_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Deptupdate_jButton.setText("Update");
        Deptupdate_jButton.setBorder(null);
        Deptupdate_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deptupdate_jButtonActionPerformed(evt);
            }
        });

        Deptdelete_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Deptdelete_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Deptdelete_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Deptdelete_jButton.setText("Delete");
        Deptdelete_jButton.setBorder(null);
        Deptdelete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deptdelete_jButtonActionPerformed(evt);
            }
        });

        Dept_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dept_jTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Dept_jTable);

        javax.swing.GroupLayout AddDeptLayout = new javax.swing.GroupLayout(AddDept);
        AddDept.setLayout(AddDeptLayout);
        AddDeptLayout.setHorizontalGroup(
            AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDeptLayout.createSequentialGroup()
                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDeptLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddDeptLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(Deptregistration_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backDeptRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddDeptLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(clearDeptRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddDeptLayout.createSequentialGroup()
                                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_jLabel1)
                                    .addComponent(mobile_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(did_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcode_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username_jLabel1)
                                    .addComponent(age_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddate_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))))
                    .addGroup(AddDeptLayout.createSequentialGroup()
                        .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddDeptLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(Deptadd_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Deptupdate_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(Deptdelete_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddDeptLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddDeptLayout.setVerticalGroup(
            AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDeptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deptregistration_jLabel)
                    .addComponent(backDeptRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_jLabel1)
                    .addComponent(did_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_jLabel1)
                    .addComponent(dname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dcode_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_jLabel1)
                    .addComponent(age_jLabel1)
                    .addComponent(ddate_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clearDeptRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deptadd_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deptupdate_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deptdelete_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPage.setBackground(new java.awt.Color(255, 204, 204));
        MainPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Type SELECT Queries");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        Emp_b.setBackground(new java.awt.Color(102, 102, 255));
        Emp_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Emp_b.setForeground(new java.awt.Color(255, 255, 255));
        Emp_b.setText("Add Employees");
        Emp_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_bActionPerformed(evt);
            }
        });

        Dept_b.setBackground(new java.awt.Color(102, 102, 255));
        Dept_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dept_b.setForeground(new java.awt.Color(255, 255, 255));
        Dept_b.setText("Add Departments");
        Dept_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dept_bActionPerformed(evt);
            }
        });

        Post_b.setBackground(new java.awt.Color(102, 102, 255));
        Post_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Post_b.setForeground(new java.awt.Color(255, 255, 255));
        Post_b.setText("Add Posts");
        Post_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Post_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Post_b)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Emp_b)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Dept_b)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Post_b)
                .addGap(38, 38, 38)
                .addComponent(Emp_b)
                .addGap(40, 40, 40)
                .addComponent(Dept_b)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(QueryResult_jTable);

        SubmitQuery.setBackground(new java.awt.Color(255, 102, 102));
        SubmitQuery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubmitQuery.setText("Submit");
        SubmitQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPageLayout = new javax.swing.GroupLayout(MainPage);
        MainPage.setLayout(MainPageLayout);
        MainPageLayout.setHorizontalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPageLayout.createSequentialGroup()
                .addGroup(MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPageLayout.createSequentialGroup()
                        .addGroup(MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPageLayout.createSequentialGroup()
                                .addGroup(MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPageLayout.createSequentialGroup()
                                        .addGap(254, 254, 254)
                                        .addComponent(SubmitQuery)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(MainPageLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(MainPageLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        MainPageLayout.setVerticalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPageLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubmitQuery))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        AddPost.setBackground(new java.awt.Color(204, 204, 255));
        AddPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        Postregistration_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        Postregistration_jLabel.setText("Post Registration");
        Postregistration_jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pcode_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        pcode_jLabel.setText("Post Code:");

        pcode_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        pcode_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pdate_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        pdate_jLabel.setText("Update Date:");

        pdate_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        pdate_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pname_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        pname_jLabel.setText("Post Name:");

        pname_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        pname_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        clearPostRegistration_jButton.setBackground(new java.awt.Color(0, 0, 0));
        clearPostRegistration_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        clearPostRegistration_jButton.setForeground(new java.awt.Color(153, 153, 255));
        clearPostRegistration_jButton.setText("Clear");
        clearPostRegistration_jButton.setBorder(null);
        clearPostRegistration_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPostRegistration_jButtonActionPerformed(evt);
            }
        });

        backPostRegistration_jButton.setBackground(new java.awt.Color(0, 0, 0));
        backPostRegistration_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        backPostRegistration_jButton.setForeground(new java.awt.Color(153, 153, 255));
        backPostRegistration_jButton.setText("Back");
        backPostRegistration_jButton.setBorder(null);
        backPostRegistration_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPostRegistration_jButtonActionPerformed(evt);
            }
        });

        Postadd_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Postadd_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Postadd_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Postadd_jButton.setText("Add");
        Postadd_jButton.setBorder(null);
        Postadd_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Postadd_jButtonActionPerformed(evt);
            }
        });

        pID_jLabel.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        pID_jLabel.setText("Post ID:");

        pid_jTextField.setBackground(new java.awt.Color(233, 233, 254));
        pid_jTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Postupdate_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Postupdate_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Postupdate_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Postupdate_jButton.setText("Update");
        Postupdate_jButton.setBorder(null);
        Postupdate_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Postupdate_jButtonActionPerformed(evt);
            }
        });

        Postdelete_jButton.setBackground(new java.awt.Color(0, 0, 0));
        Postdelete_jButton.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Postdelete_jButton.setForeground(new java.awt.Color(153, 153, 255));
        Postdelete_jButton.setText("Delete");
        Postdelete_jButton.setBorder(null);
        Postdelete_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Postdelete_jButtonActionPerformed(evt);
            }
        });

        Post_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Post_jTableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(Post_jTable);

        javax.swing.GroupLayout AddPostLayout = new javax.swing.GroupLayout(AddPost);
        AddPost.setLayout(AddPostLayout);
        AddPostLayout.setHorizontalGroup(
            AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPostLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pID_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pdate_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPostLayout.createSequentialGroup()
                        .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pdate_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(pid_jTextField))
                        .addGap(130, 130, 130)
                        .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddPostLayout.createSequentialGroup()
                                .addComponent(pname_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddPostLayout.createSequentialGroup()
                                .addComponent(pcode_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pcode_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddPostLayout.createSequentialGroup()
                            .addComponent(Postadd_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(Postupdate_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(Postdelete_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPostLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(clearPostRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AddPostLayout.createSequentialGroup()
                                    .addComponent(Postregistration_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(179, 179, 179)
                                    .addComponent(backPostRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addGroup(AddPostLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        AddPostLayout.setVerticalGroup(
            AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Postregistration_jLabel)
                    .addComponent(backPostRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pID_jLabel)
                    .addComponent(pid_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pname_jLabel)
                    .addComponent(pname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcode_jLabel)
                    .addComponent(pcode_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdate_jLabel)
                    .addComponent(pdate_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(clearPostRegistration_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Postadd_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postupdate_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postdelete_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        MainPanel.setPreferredSize(new java.awt.Dimension(543, 609));

        LoginPanel.setBackground(new java.awt.Color(153, 153, 255));
        LoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loginuser_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginuser_jLabel.setText("Username");

        loginpass_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginpass_jLabel.setText("Password");

        user_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user_jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        login_jButton.setBackground(new java.awt.Color(0, 0, 0));
        login_jButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login_jButton.setForeground(new java.awt.Color(153, 204, 255));
        login_jButton.setText("Login");
        login_jButton.setRequestFocusEnabled(false);
        login_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jButtonActionPerformed(evt);
            }
        });

        loginclear_jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginclear_jButton.setText("Clear");
        loginclear_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginclear_jButtonActionPerformed(evt);
            }
        });

        pass_jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pass_jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_jPasswordField.setToolTipText("");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginclear_jButton))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(login_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(loginuser_jLabel))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(loginpass_jLabel))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(user_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pass_jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(loginuser_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(loginpass_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(login_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(loginclear_jButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 7, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddPost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddDept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Dept_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dept_bActionPerformed
        // TODO add your handling code here:
        MainPage.setVisible(false);
        AddDept.setVisible(true);
        AddEmp.setVisible(false);
        AddPost.setVisible(false);
        
        DisplayDeptDetails();
    }//GEN-LAST:event_Dept_bActionPerformed

    private void SubmitQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitQueryActionPerformed
        // TODO add your handling code here:
        QueryResult_jTable.setModel(new DefaultTableModel());

        query = jTextArea1.getText();
        DisplayDetails(query);

    }//GEN-LAST:event_SubmitQueryActionPerformed

    private void Post_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Post_bActionPerformed
        // TODO add your handling code here:
        MainPage.setVisible(false);
        AddDept.setVisible(false);
        AddEmp.setVisible(false);
        AddPost.setVisible(true);
        
        DisplayPostDetails();

    }//GEN-LAST:event_Post_bActionPerformed

    private void clearEmpRegistration_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEmpRegistration_jButtonActionPerformed
        // Set empty strings in the JTextFields.
        fname_jTextField.setText("");
        lname_jTextField.setText("");
        address_jTextArea.setText("");
        salary_jTextField.setText("");
        dept_jTextField.setText("");
        post_jTextField.setText("");
        date_jTextField.setText("");
        email_jTextField.setText("");

        Emp_jTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_clearEmpRegistration_jButtonActionPerformed

    private void backEmpRegistration_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEmpRegistration_jButtonActionPerformed
        // Change the visibility of the components according to the requirement
        AddDept.setVisible(false);
        AddEmp.setVisible(false);
        AddPost.setVisible(false);
        MainPage.setVisible(true);
    }//GEN-LAST:event_backEmpRegistration_jButtonActionPerformed

    private void EmpValidation() {
        fname = fname_jTextField.getText();
        lname = lname_jTextField.getText();
        address = address_jTextArea.getText();
        email = email_jTextField.getText();
        salary = salary_jTextField.getText();
        dept_id = dept_jTextField.getText();
        post_id = post_jTextField.getText();
        update_date = date_jTextField.getText();

        count = 0;
        if (fname.equals("") || lname.equals("") || address.equals("") || email.equals("") || salary.equals("") || dept_id.equals("") || post_id.equals("") || update_date.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please ensure that all fields are filled.");
            count = 1;
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.salary_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The salary must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.dept_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The department id must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.post_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The post id must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
    }

    private void Empadd_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empadd_jButtonActionPerformed
        EmpValidation();
        if (count == 0) {
            System.out.println("Details Validated");
            query = "insert into emp_tb (emp_name, emp_last_name, emp_address, emp_email, emp_salary, dept_id, post_id, update_date) values('" + fname + "','" + lname + "','" + address + "','" + email + "','" + salary + "','" + dept_id + "','" + post_id + "','" + update_date + "')";
            try {
                int result = st.executeUpdate(query);
                Emp_jTable.setModel(new DefaultTableModel());
                DisplayEmpDetails();
                JOptionPane.showMessageDialog(rootPane, result + " Record Inserted");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
    }//GEN-LAST:event_Empadd_jButtonActionPerformed

    private void DisplayEmpDetails() {
        // TODO add your handling code here:
        query = "select * from emp_tb";
        try {
            rs = st.executeQuery(query); // Execute query
            Emp_jTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void Empupdate_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empupdate_jButtonActionPerformed
        // TODO add your handling code here:
        EmpValidation();

        if (count == 0) {
            int row = Emp_jTable.getSelectedRow();
            String value = (Emp_jTable.getModel().getValueAt(row, 0).toString());
            query = "update emp_tb set emp_name='" + fname + "',emp_last_name='" + lname + "',emp_address='" + address + "',emp_email='" + email + "',emp_salary='" + salary + "',dept_id='" + dept_id + "',post_id='" + post_id + "',update_date='" + update_date + "' where emp_id=" + value;

            try {
                int result = st.executeUpdate(query);
                model = (DefaultTableModel) Emp_jTable.getModel();
                model.setRowCount(0);

                Emp_jTable.setModel(new DefaultTableModel());  //clears previous data
                DisplayEmpDetails();
                JOptionPane.showMessageDialog(rootPane, result + " Record Updated");

            } catch (SQLException ex) {
                Logger.getLogger(Registration.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Empupdate_jButtonActionPerformed

    private void Empdelete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empdelete_jButtonActionPerformed
        // TODO add your handling code here:
        EmpValidation();
        if (count == 0) {
            int row = Emp_jTable.getSelectedRow();
            String value = (Emp_jTable.getModel().getValueAt(row, 0).toString());
            query = "delete from emp_tb where emp_id= " + value;

            int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this record?", "DELETE", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                try {
                    int result = st.executeUpdate(query);

                    Emp_jTable.setModel(new DefaultTableModel());
                    DisplayEmpDetails();
                    JOptionPane.showMessageDialog(rootPane, result + " Record Deleted.");

                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_Empdelete_jButtonActionPerformed

    private void Emp_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_jTableMouseClicked
        // TODO add your handling code here:
        int i = Emp_jTable.getSelectedRow();
        model = (DefaultTableModel) Emp_jTable.getModel();

        fname_jTextField.setText(model.getValueAt(i, 1).toString());
        lname_jTextField.setText(model.getValueAt(i, 2).toString());
        address_jTextArea.setText(model.getValueAt(i, 3).toString());
        email_jTextField.setText(model.getValueAt(i, 4).toString());
        salary_jTextField.setText(model.getValueAt(i, 5).toString());
        dept_jTextField.setText(model.getValueAt(i, 6).toString());
        post_jTextField.setText(model.getValueAt(i, 7).toString());
        date_jTextField.setText(model.getValueAt(i, 8).toString());
    }//GEN-LAST:event_Emp_jTableMouseClicked

    private void clearDeptRegistration_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDeptRegistration_jButtonActionPerformed
        // TODO add your handling code here:
        did_jTextField.setText("");
        dcode_jTextField.setText("");
        dname_jTextField.setText("");
        ddate_jTextField.setText("");
        Dept_jTable.setModel(new DefaultTableModel());
        
    }//GEN-LAST:event_clearDeptRegistration_jButtonActionPerformed

    private void backDeptRegistration_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDeptRegistration_jButtonActionPerformed
        // TODO add your handling code here:
        AddDept.setVisible(false);
        AddEmp.setVisible(false);
        AddPost.setVisible(false);
        MainPage.setVisible(true);
    }//GEN-LAST:event_backDeptRegistration_jButtonActionPerformed

    private void DisplayDeptDetails() {
        // TODO add your handling code here:
        query = "select * from dept_tb";
        try {
            rs = st.executeQuery(query); // Execute query
            Dept_jTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void DeptValidation() {
        did = did_jTextField.getText();
        dcode = dcode_jTextField.getText();
        dname = dname_jTextField.getText();
        ddate = ddate_jTextField.getText();

        count = 0;
        if (did.equals("") || dname.equals("") || dname.equals("") || ddate.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please ensure that all fields are filled.");
            count = 1;
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.did_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The department id must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.dcode_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The department code must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
    }

    private void Deptadd_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deptadd_jButtonActionPerformed
        // TODO add your handling code here:
        DeptValidation();
        if (count == 0) {
            System.out.println("Details Validated");
            query = "insert into dept_tb (dept_id, dept_code, dept_name, update_date) values('" + did + "','" + dcode + "','" + dname + "','" + ddate + "')";
            try {
                int result = st.executeUpdate(query);
                Dept_jTable.setModel(new DefaultTableModel());
                DisplayDeptDetails();
                JOptionPane.showMessageDialog(rootPane, result + " Record Inserted");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
    }//GEN-LAST:event_Deptadd_jButtonActionPerformed

    private void Deptupdate_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deptupdate_jButtonActionPerformed
        // TODO add your handling code here:
        DeptValidation();

        if (count == 0) {
            int row = Dept_jTable.getSelectedRow();
            String value = (Dept_jTable.getModel().getValueAt(row, 0).toString());
            query = "update dept_tb set dept_code='" + dcode + "',dept_name='" + dname + "',update_date='" + ddate + "' where dept_id=" + value;

            try {
                int result = st.executeUpdate(query);
                model = (DefaultTableModel) Dept_jTable.getModel();
                model.setRowCount(0);

                Post_jTable.setModel(new DefaultTableModel());  //clears previous data
                DisplayDeptDetails();
                JOptionPane.showMessageDialog(rootPane, result + " Record Updated");

            } catch (SQLException ex) {
                Logger.getLogger(Registration.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Deptupdate_jButtonActionPerformed

    private void Deptdelete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deptdelete_jButtonActionPerformed
        // TODO add your handling code here:
        DeptValidation();
        if (count == 0) {
            int row = Dept_jTable.getSelectedRow();
            String value = (Dept_jTable.getModel().getValueAt(row, 0).toString());
            query = "delete from dept_tb where dept_id= " + value;

            int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this record?", "DELETE", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                try {
                    int result = st.executeUpdate(query);

                    Dept_jTable.setModel(new DefaultTableModel());
                    DisplayPostDetails();
                    JOptionPane.showMessageDialog(rootPane, result + " Record Deleted.");

                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_Deptdelete_jButtonActionPerformed

    private void Dept_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dept_jTableMouseClicked
        // TODO add your handling code here:
        int i = Dept_jTable.getSelectedRow();
        model = (DefaultTableModel) Dept_jTable.getModel();

        did_jTextField.setText(model.getValueAt(i, 0).toString());
        dcode_jTextField.setText(model.getValueAt(i, 1).toString());
        dname_jTextField.setText(model.getValueAt(i, 2).toString());
        ddate_jTextField.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_Dept_jTableMouseClicked

    private void clearPostRegistration_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPostRegistration_jButtonActionPerformed
        // TODO add your handling code here:
        pid_jTextField.setText("");
        pcode_jTextField.setText("");
        pname_jTextField.setText("");
        pdate_jTextField.setText("");
        Post_jTable.setModel(new DefaultTableModel());

    }//GEN-LAST:event_clearPostRegistration_jButtonActionPerformed

    private void backPostRegistration_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPostRegistration_jButtonActionPerformed
        // TODO add your handling code here:
        AddDept.setVisible(false);
        AddEmp.setVisible(false);
        AddPost.setVisible(false);
        MainPage.setVisible(true);
    }//GEN-LAST:event_backPostRegistration_jButtonActionPerformed

    private void DisplayPostDetails() {
        // TODO add your handling code here:
        query = "select * from post_tb";
        try {
            rs = st.executeQuery(query); // Execute query
            Post_jTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void PostValidation() {
        pid = pid_jTextField.getText();
        pcode = pcode_jTextField.getText();
        pname = pname_jTextField.getText();
        pdate = pdate_jTextField.getText();

        count = 0;
        if (pid.equals("") || pcode.equals("") || pname.equals("") || pdate.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please ensure that all fields are filled.");
            count = 1;
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.pid_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The post ID must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
        if (count == 0) {
            try {
                Integer.parseInt(this.pcode_jTextField.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "The post code must be an integer number.", "ATTENTION!", JOptionPane.ERROR_MESSAGE);
                count = 1;
            }
        }
    }

    private void Postadd_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Postadd_jButtonActionPerformed
        // TODO add your handling code here:
        PostValidation();
        if (count == 0) {
            System.out.println("Details Validated");
            query = "insert into post_tb (post_id, post_code, post_name, update_date) values('" + pid + "','" + pcode + "','" + pname + "','" + pdate + "')";
            try {
                int result = st.executeUpdate(query);
                Post_jTable.setModel(new DefaultTableModel());
                DisplayPostDetails();
                JOptionPane.showMessageDialog(rootPane, result + " Record Inserted");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
    }//GEN-LAST:event_Postadd_jButtonActionPerformed

    private void Postupdate_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Postupdate_jButtonActionPerformed
        // TODO add your handling code here:
        PostValidation();

        if (count == 0) {
            int row = Post_jTable.getSelectedRow();
            String value = (Post_jTable.getModel().getValueAt(row, 0).toString());
            query = "update post_tb set post_code='" + pcode + "',post_name='" + pname + "',update_date='" + pdate + "' where post_id=" + value;

            try {
                int result = st.executeUpdate(query);
                model = (DefaultTableModel) Post_jTable.getModel();
                model.setRowCount(0);

                Post_jTable.setModel(new DefaultTableModel());  //clears previous data
                DisplayPostDetails();
                JOptionPane.showMessageDialog(rootPane, result + " Record Updated");

            } catch (SQLException ex) {
                Logger.getLogger(Registration.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Postupdate_jButtonActionPerformed

    private void Postdelete_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Postdelete_jButtonActionPerformed
        // TODO add your handling code here:
        PostValidation();
        if (count == 0) {
            int row = Post_jTable.getSelectedRow();
            String value = (Post_jTable.getModel().getValueAt(row, 0).toString());
            query = "delete from post_tb where post_id= " + value;

            int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this record?", "DELETE", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                try {
                    int result = st.executeUpdate(query);

                    Post_jTable.setModel(new DefaultTableModel());
                    DisplayPostDetails();
                    JOptionPane.showMessageDialog(rootPane, result + " Record Deleted.");

                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_Postdelete_jButtonActionPerformed

    private void Post_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Post_jTableMouseClicked
        // TODO add your handling code here:

        int i = Post_jTable.getSelectedRow();
        model = (DefaultTableModel) Post_jTable.getModel();

        pid_jTextField.setText(model.getValueAt(i, 0).toString());
        pcode_jTextField.setText(model.getValueAt(i, 1).toString());
        pname_jTextField.setText(model.getValueAt(i, 2).toString());
        pdate_jTextField.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_Post_jTableMouseClicked

    private void Emp_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_bActionPerformed
        // TODO add your handling code here:
        MainPage.setVisible(false);
        AddEmp.setVisible(true);
        AddDept.setVisible(false);
        AddPost.setVisible(false);
        
        DisplayEmpDetails();
    }//GEN-LAST:event_Emp_bActionPerformed

    private void login_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jButtonActionPerformed
        // TODO add your handling code here:
        String user = user_jTextField.getText();
        String user1= user.toUpperCase();
        String pass = pass_jPasswordField.getText();
        String pass1= pass.toUpperCase();
        try {
            if ("ADMIN".equals(user1) && "@ADMIN".equals(pass1)) {
                JOptionPane.showMessageDialog(rootPane, "Login Successful :)");
                MainPanel.setVisible(false);
                LoginPanel.setVisible(false);
                MainPage.setVisible(true);
                AddEmp.setVisible(false);
                AddDept.setVisible(false);
                AddPost.setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Invalid Credentials :(");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_login_jButtonActionPerformed

    private void loginclear_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginclear_jButtonActionPerformed
        // TODO add your handling code here:
        user_jTextField.setText("");
        pass_jPasswordField.setText("");
    }//GEN-LAST:event_loginclear_jButtonActionPerformed

    private void DisplayDetails(String query) {
        // TODO add your handling code here:
        try {
            rs = st.executeQuery(query); // Execute query
            QueryResult_jTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDept;
    private javax.swing.JPanel AddEmp;
    private javax.swing.JPanel AddPost;
    private javax.swing.JButton Dept_b;
    private javax.swing.JTable Dept_jTable;
    private javax.swing.JButton Deptadd_jButton;
    private javax.swing.JButton Deptdelete_jButton;
    private javax.swing.JLabel Deptregistration_jLabel;
    private javax.swing.JButton Deptupdate_jButton;
    private javax.swing.JButton Emp_b;
    private javax.swing.JTable Emp_jTable;
    private javax.swing.JButton Empadd_jButton;
    private javax.swing.JButton Empdelete_jButton;
    private javax.swing.JLabel Empregistration_jLabel;
    private javax.swing.JButton Empupdate_jButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainPage;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Post_b;
    private javax.swing.JTable Post_jTable;
    private javax.swing.JButton Postadd_jButton;
    private javax.swing.JButton Postdelete_jButton;
    private javax.swing.JLabel Postregistration_jLabel;
    private javax.swing.JButton Postupdate_jButton;
    private javax.swing.JTable QueryResult_jTable;
    private javax.swing.JButton SubmitQuery;
    private javax.swing.JLabel address_jLabel;
    private javax.swing.JTextArea address_jTextArea;
    private javax.swing.JLabel age_jLabel1;
    private javax.swing.JButton backDeptRegistration_jButton;
    private javax.swing.JButton backEmpRegistration_jButton;
    private javax.swing.JButton backPostRegistration_jButton;
    private javax.swing.JButton clearDeptRegistration_jButton;
    private javax.swing.JButton clearEmpRegistration_jButton;
    private javax.swing.JButton clearPostRegistration_jButton;
    private javax.swing.JLabel date_jLabel;
    private javax.swing.JTextField date_jTextField;
    private javax.swing.JTextField dcode_jTextField;
    private javax.swing.JTextField ddate_jTextField;
    private javax.swing.JTextField dept_jTextField;
    private javax.swing.JLabel did_jLabel;
    private javax.swing.JTextField did_jTextField;
    private javax.swing.JTextField dname_jTextField;
    private javax.swing.JLabel email_jLabel;
    private javax.swing.JTextField email_jTextField;
    private javax.swing.JLabel fname_jLabel;
    private javax.swing.JTextField fname_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lname_jLabel;
    private javax.swing.JTextField lname_jTextField;
    private javax.swing.JButton login_jButton;
    private javax.swing.JButton loginclear_jButton;
    private javax.swing.JLabel loginpass_jLabel;
    private javax.swing.JLabel loginuser_jLabel;
    private javax.swing.JLabel mobile_jLabel1;
    private javax.swing.JLabel name_jLabel1;
    private javax.swing.JLabel pID_jLabel;
    private javax.swing.JPasswordField pass_jPasswordField;
    private javax.swing.JLabel pcode_jLabel;
    private javax.swing.JTextField pcode_jTextField;
    private javax.swing.JLabel pdate_jLabel;
    private javax.swing.JTextField pdate_jTextField;
    private javax.swing.JLabel pid_jLabel;
    private javax.swing.JTextField pid_jTextField;
    private javax.swing.JLabel pname_jLabel;
    private javax.swing.JTextField pname_jTextField;
    private javax.swing.JTextField post_jTextField;
    private javax.swing.JLabel salary_jLabel;
    private javax.swing.JTextField salary_jTextField;
    private javax.swing.JTextField user_jTextField;
    private javax.swing.JLabel username_jLabel1;
    // End of variables declaration//GEN-END:variables
}
